# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.6.5

pipelines:
  default:
    - step:
        caches:
          - pip
        script: # Modify the commands below to build your repository.
          - pip install -r requirements.txt
  branches:
    master:
      - step:
          script:
            - echo "Merging to master; please MAKE SURE EVERYTHING IS STABLE"
            - echo "Testing mainwindow_controller.py for non-runtime errors..."
            - python -m unittest mainwindow_controller.py
            - echo "Done!"
    develop:
      - step:
          cache:
            - pip
          script:
            - echo "Installing dependencies..."
            - pip install -r requirements.txt
            - sudo apt install libgl1-mesa-glx
            - echo "Running integration tests for mainwindow_controller..."
            - echo "Testing for non runtime errors..."
            - python -m unittest mainwindow_controller.py
            - echo "Everything OK."

          
